"""empty message

Revision ID: af4b4b5506a3
Revises: 9069946440c2
Create Date: 2017-04-28 15:40:42.690427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4b4b5506a3'
down_revision = '9069946440c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('adr_city', sa.String(), nullable=True))
    op.add_column('place', sa.Column('adr_state', sa.String(length=2), nullable=True))
    op.add_column('place', sa.Column('adr_street', sa.String(), nullable=True))
    op.add_column('place', sa.Column('adr_zip', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'adr_zip')
    op.drop_column('place', 'adr_street')
    op.drop_column('place', 'adr_state')
    op.drop_column('place', 'adr_city')
    # ### end Alembic commands ###
